# Generated by Django 5.1.5 on 2025-01-29 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_options_alter_postattachment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='coment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Автор')),
                ('content', models.TextField(verbose_name='Комментарий')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='Время публикации коментария')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post', verbose_name='Пост к которому относится')),
            ],
        ),
    ]
