# Generated by Django 5.1.5 on 2025-02-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_post_time_stamp_comment_delete_coment'),
    ]

    operations = [
        migrations.AddField(
            model_name='postattachment',
            name='name',
            field=models.CharField(blank=True, verbose_name='Название файла'),
        ),
    ]
